public class calculator1 {
    public static void Additon(integer a,integer b){
        System.debug('the addition of two number is'+(a+b));
    }
    public static void substraction(integer a,integer b){
        System.debug('Substraction of two numbwe is'+(a-b));
    }
     public static void multiplication(integer a,integer b){
        System.debug('Substraction of two numbwe is'+(a*b));
    }
     public static void Division(integer a,integer b){
        System.debug('Substraction of two numbwe is'+(a/b));
    }

}