public class Calculator {
    public static void Addition(integer x,integer y){
        System.debug('the addition of two number is:'+(x+y));
    }
    public static void substraction(integer x,integer y){
        System.debug('The substraction of two number is:' +(x-y));
        
    }
    public static void multiplication(integer x,integer y){
        System.debug('The multiplication two number is:'+(x*y));
    }
    
    public static void division(integer x,integer y){
        System.debug('the division of two number is:'+(x/y));
    }
    public static void modulus(integer x,integer y){
        System.debug('the modulus of two number is:'+Math.mod(x,y));
    }
    
}