public class Soqlqueryeg {
    
    
    public static void test(){
   /*OQL-Salesforce object query language.
        One object or releted object.
        
     syntax:
    select <fieldsname> from <objectname>
        Select name,phone from account
        where
        group by
        having
        order by
        limit
        offset
        all rows
        for update
         100 soql queries within a transaction
        
         Select name,phone from account
         Select name,phone from account
         Select name,phone from account
         Select name,phone from account
        50000 records */
        
       
        
        
        
        
    }
        
        
        

}